version: '3.8'

services:
  duel_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: duel_app_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - duel_app_network

networks:
  duel_app_network:
    driver: bridge