FROM node:24-alpine AS base

# Set working directory in container
WORKDIR /usr/local/app

################## CLIENT STAGES ##################

###################################################
# Stage: client-base
#
# This stage is used as the base for the client-dev and client-build stages,
# since there are common steps needed for each.
###################################################
FROM base AS client-base
# Copy package files
COPY client/package.json client/package-lock.json ./
RUN npm install
COPY client/.eslintrc.cjs client/index.html client/vite.config.ts ./
COPY client/public ./public
COPY client/src ./src

###################################################
# Stage: client-dev
#
###################################################

# Expose the port Vite runs on
EXPOSE 5173

FROM client-base AS client-dev
# Command to run the development server
CMD ["npm", "run", "dev", "--host", "0.0.0.0"]
